# fly.toml app configuration file generated for ipl-finder on 2026-05-19T18:47:54+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ipl-finder'
primary_region = 'sin'

[build]
  [build.args]
    VITE_SUPABASE_URL = "https://lfxkabhzfgenpqfnhjyw.supabase.co"
    VITE_SUPABASE_PUBLISHABLE_KEY = "sb_publishable_jtADEBQ9FAYPaSqU5iabtg_m356QDIw"
    VITE_PORTAL_URL = "https://portal.veryresto.com"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpus = 1
  memory_mb = 256
